# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df51c8236fe3e761a462e9f1d1c7ae76ea7ef61acd308ec5969f2dd3174c3e22ce875236daf3bf6ab0a3590eebd89c733f0da46c503c44234397ee8daf47e2be

test:
  secret_key_base: ec500ba24b207dd619c599ccb3c1a161b13e35a0351990aa3056e61c2ad1fba1b076b690ca97f85e5e3ab61c0544a062ba0d42a40531e9966c4483dd22d03465

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
